// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

import '../frb_generated.dart';
import 'error.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

/// Get Strike node information including balance
Future<LightningNodeInfo> strikeGetInfo({
  required StrikeLightningConfig config,
}) => RustLib.instance.api.crateApiLightningStrikeGetInfo(config: config);

/// Create a Lightning invoice with Strike
Future<LightningTransaction> strikeCreateInvoice({
  required StrikeLightningConfig config,
  required CreateInvoiceParams params,
}) => RustLib.instance.api.crateApiLightningStrikeCreateInvoice(
  config: config,
  params: params,
);

/// Pay a Lightning invoice with Strike
Future<PayInvoiceResponse> strikePayInvoice({
  required StrikeLightningConfig config,
  required PayInvoiceParams params,
}) => RustLib.instance.api.crateApiLightningStrikePayInvoice(
  config: config,
  params: params,
);

/// Lookup a Lightning invoice by payment hash
Future<LightningTransaction> strikeLookupInvoice({
  required StrikeLightningConfig config,
  required String paymentHash,
}) => RustLib.instance.api.crateApiLightningStrikeLookupInvoice(
  config: config,
  paymentHash: paymentHash,
);

/// List Lightning transactions
Future<List<LightningTransaction>> strikeListTransactions({
  required StrikeLightningConfig config,
  required ListTransactionsParams params,
}) => RustLib.instance.api.crateApiLightningStrikeListTransactions(
  config: config,
  params: params,
);

/// Parameters for creating a Lightning invoice
class CreateInvoiceParams {
  /// Amount in millisatoshis
  final PlatformInt64? amountMsats;

  /// Invoice description/memo
  final String? description;

  /// Expiry time in seconds
  final PlatformInt64? expiry;

  const CreateInvoiceParams({
    this.amountMsats,
    this.description,
    this.expiry,
  });

  @override
  int get hashCode =>
      amountMsats.hashCode ^ description.hashCode ^ expiry.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CreateInvoiceParams &&
          runtimeType == other.runtimeType &&
          amountMsats == other.amountMsats &&
          description == other.description &&
          expiry == other.expiry;
}

/// Lightning node information
class LightningNodeInfo {
  /// Node alias/name
  final String alias;

  /// Node public key
  final String publicKey;

  /// Total send balance in millisatoshis
  final PlatformInt64 sendBalanceMsats;

  /// Total receive balance in millisatoshis
  final PlatformInt64 receiveBalanceMsats;

  const LightningNodeInfo({
    required this.alias,
    required this.publicKey,
    required this.sendBalanceMsats,
    required this.receiveBalanceMsats,
  });

  @override
  int get hashCode =>
      alias.hashCode ^
      publicKey.hashCode ^
      sendBalanceMsats.hashCode ^
      receiveBalanceMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightningNodeInfo &&
          runtimeType == other.runtimeType &&
          alias == other.alias &&
          publicKey == other.publicKey &&
          sendBalanceMsats == other.sendBalanceMsats &&
          receiveBalanceMsats == other.receiveBalanceMsats;
}

/// Lightning invoice/transaction
class LightningTransaction {
  /// Transaction type
  final String type;

  /// Invoice/payment request string
  final String invoice;

  /// Payment hash
  final String paymentHash;

  /// Amount in millisatoshis
  final PlatformInt64 amountMsats;

  /// Transaction description/memo
  final String description;

  /// Creation timestamp
  final PlatformInt64 createdAt;

  /// Expiration timestamp
  final PlatformInt64 expiresAt;

  /// Settlement timestamp (0 if not paid)
  final PlatformInt64 settledAt;

  /// Fees paid in millisatoshis
  final PlatformInt64 feesPaid;

  const LightningTransaction({
    required this.type,
    required this.invoice,
    required this.paymentHash,
    required this.amountMsats,
    required this.description,
    required this.createdAt,
    required this.expiresAt,
    required this.settledAt,
    required this.feesPaid,
  });

  @override
  int get hashCode =>
      type.hashCode ^
      invoice.hashCode ^
      paymentHash.hashCode ^
      amountMsats.hashCode ^
      description.hashCode ^
      createdAt.hashCode ^
      expiresAt.hashCode ^
      settledAt.hashCode ^
      feesPaid.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LightningTransaction &&
          runtimeType == other.runtimeType &&
          type == other.type &&
          invoice == other.invoice &&
          paymentHash == other.paymentHash &&
          amountMsats == other.amountMsats &&
          description == other.description &&
          createdAt == other.createdAt &&
          expiresAt == other.expiresAt &&
          settledAt == other.settledAt &&
          feesPaid == other.feesPaid;
}

/// Parameters for listing transactions
class ListTransactionsParams {
  /// Offset for pagination
  final PlatformInt64 from;

  /// Limit number of results
  final PlatformInt64 limit;

  /// Optional search filter
  final String? search;

  const ListTransactionsParams({
    required this.from,
    required this.limit,
    this.search,
  });

  @override
  int get hashCode => from.hashCode ^ limit.hashCode ^ search.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ListTransactionsParams &&
          runtimeType == other.runtimeType &&
          from == other.from &&
          limit == other.limit &&
          search == other.search;
}

/// Parameters for paying a Lightning invoice
class PayInvoiceParams {
  /// BOLT11 invoice string to pay
  final String invoice;

  /// Maximum fee percentage (e.g., 1.0 for 1%)
  final double? feeLimitPercentage;

  const PayInvoiceParams({
    required this.invoice,
    this.feeLimitPercentage,
  });

  @override
  int get hashCode => invoice.hashCode ^ feeLimitPercentage.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PayInvoiceParams &&
          runtimeType == other.runtimeType &&
          invoice == other.invoice &&
          feeLimitPercentage == other.feeLimitPercentage;
}

/// Response from paying an invoice
class PayInvoiceResponse {
  /// Payment hash
  final String paymentHash;

  /// Payment preimage
  final String preimage;

  /// Fee paid in millisatoshis
  final PlatformInt64 feeMsats;

  const PayInvoiceResponse({
    required this.paymentHash,
    required this.preimage,
    required this.feeMsats,
  });

  @override
  int get hashCode =>
      paymentHash.hashCode ^ preimage.hashCode ^ feeMsats.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PayInvoiceResponse &&
          runtimeType == other.runtimeType &&
          paymentHash == other.paymentHash &&
          preimage == other.preimage &&
          feeMsats == other.feeMsats;
}

/// Configuration for Strike Lightning payments
class StrikeLightningConfig {
  /// Strike API key for authentication
  final String apiKey;

  /// Optional custom base URL (defaults to https://api.strike.me/v1)
  final String? baseUrl;

  /// Optional SOCKS5 proxy URL for Tor support
  final String? socks5Proxy;

  /// Whether to accept invalid SSL certificates (for development)
  final bool? acceptInvalidCerts;

  /// HTTP timeout in seconds
  final PlatformInt64? httpTimeout;

  const StrikeLightningConfig({
    required this.apiKey,
    this.baseUrl,
    this.socks5Proxy,
    this.acceptInvalidCerts,
    this.httpTimeout,
  });

  @override
  int get hashCode =>
      apiKey.hashCode ^
      baseUrl.hashCode ^
      socks5Proxy.hashCode ^
      acceptInvalidCerts.hashCode ^
      httpTimeout.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is StrikeLightningConfig &&
          runtimeType == other.runtimeType &&
          apiKey == other.apiKey &&
          baseUrl == other.baseUrl &&
          socks5Proxy == other.socks5Proxy &&
          acceptInvalidCerts == other.acceptInvalidCerts &&
          httpTimeout == other.httpTimeout;
}
